[package]
name = "codepage_converter"
version = "1.0.0"
authors = ["nyfair <nyfair2012@gmail.com>"]

[dependencies.encoding_rs]
version = "*"
default-features = false
features = ["simd-accel", "fast-legacy-encode", "alloc"]

[profile.release]
lto = true
