name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [win32, win64]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile Stable
      run: |
        cargo build --release
        move target\release\*.exe .
        7z a ${{ matrix.os }}-stable.7z *.exe
        del *.exe
    - name: Switch Nightly Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2024-02-04
        override: true
    - name: Compile Nightly
      run: |
        del Cargo.toml
        move Nightly.toml Cargo.toml
        cargo build --release
        move target\release\*.exe .
        7z a ${{ matrix.os }}.7z *.exe
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.os }}*.7z
        tag: latest
        overwrite: true
        file_glob: true
